title: Robin Hunter # your name (or website title) here
![Test Image](images/Skype temp.jpg)
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring data analyst 
  <br><br>
  Please feel free to review my data analyst projects, thank you 
  <br><br>
  <a href="https://www.linkedin.com/in/robinhunter11/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
