title: Robin Hunter # your name (or website title) here
logo: "images/Skype temp.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Global Reporting Analyst at Coates Group 
  <br><br>
  Please feel free to review the projects I completed in my spare time! 
  <br><br>
  <a href="https://www.linkedin.com/in/robinhunter11/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
